// "use-client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ksFAb3C3VlO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { DashboardContent } from "./dashboardContent";

export function Dashboard() {
  return (
    <div
      className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900"
      style={{
        minHeight: '100vh',
        height: 'auto'
      }}
    >
      <DashboardContent />
    </div>
  );
}
