/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/afxtlPvSAW5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { MountainIcon } from "./ui/MountainIcon";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export function Done() {
  return (
    <div className="mx-4 my-auto flex max-w-md flex-col items-center justify-center space-y-6 rounded-lg bg-white p-8 shadow-lg dark:bg-gray-900">
      <MountainIcon className="h-36 w-36 text-gray-900 dark:text-gray-50" />
      <div className="space-y-2 text-center">
        <h2 className="text-3xl font-bold tracking-tighter text-gray-900 dark:text-gray-50">
          Congratulations!
        </h2>
        <p className="text-gray-500 dark:text-gray-400">
          You have successfully completed guest registration. We can't wait to
          see you!
        </p>
      </div>
    </div>
  );
}
