/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wMru8gmXRbv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Calendar } from "@/components/ui/calendar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Separator } from "@/components/ui/separator"
import { ResponsiveLine } from "@nivo/line"

export function NewDashboard() {
  return (
    (<div className="flex h-screen w-full">
      <div className="bg-green-900 text-white w-64 p-6 flex flex-col gap-6">
        <div className="flex items-center gap-2">
          <HomeIcon className="w-6 h-6" />
          <span className="text-lg font-semibold">HOA Dashboard</span>
        </div>
        <nav className="flex flex-col gap-2">
          <Link
            className="flex items-center gap-2 px-4 py-2 rounded-md hover:bg-green-800 transition-colors"
            href="#">
            <UsersIcon className="w-5 h-5" />
            <span>Guests</span>
          </Link>
          <Link
            className="flex items-center gap-2 px-4 py-2 rounded-md hover:bg-green-800 transition-colors"
            href="#">
            <CalendarIcon className="w-5 h-5" />
            <span>Calendar</span>
          </Link>
          <Link
            className="flex items-center gap-2 px-4 py-2 rounded-md hover:bg-green-800 transition-colors"
            href="#">
            <PlusIcon className="w-5 h-5" />
            <span>Add Guest</span>
          </Link>
          <Link
            className="flex items-center gap-2 px-4 py-2 rounded-md hover:bg-green-800 transition-colors"
            href="#">
            <KeyIcon className="w-5 h-5" />
            <span>Access Management</span>
          </Link>
          <Link
            className="flex items-center gap-2 px-4 py-2 rounded-md hover:bg-green-800 transition-colors"
            href="#">
            <BarChartIcon className="w-5 h-5" />
            <span>Analytics</span>
          </Link>
        </nav>
      </div>
      <div className="flex-1 flex flex-col">
        <header className="bg-white border-b px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img
              alt="HOA Logo"
              className="w-10 h-10"
              height={40}
              src="/placeholder.svg"
              style={{
                aspectRatio: "40/40",
                objectFit: "cover",
              }}
              width={40} />
            <h1 className="text-2xl font-semibold">Homeowners Association</h1>
          </div>
          <div className="flex items-center gap-4">
            <Button size="icon" variant="ghost">
              <BellIcon className="w-6 h-6" />
              <span className="sr-only">Notifications</span>
            </Button>
            <Avatar className="w-10 h-10 border">
              <AvatarImage alt="Admin" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </header>
        <main
          className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-6">
          <Card>
            <CardHeader>
              <CardTitle>Active Guests</CardTitle>
              <CardDescription>View a list of all active guests in the community.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div className="text-4xl font-bold">24</div>
                <Button size="sm" variant="outline">
                  View All
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Visits</CardTitle>
              <CardDescription>See a calendar view of all upcoming guest visits.</CardDescription>
            </CardHeader>
            <CardContent>
              <Calendar
                className="p-0 [&_td]:w-10 [&_td]:h-10 [&_th]:w-10 [&_[name=day]]:w-10 [&_[name=day]]:h-10 [&>div]:space-x-0 [&>div]:gap-6"
                mode="single"
                numberOfMonths={1} />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Add New Guest</CardTitle>
              <CardDescription>Create a new guest reservation for your community.</CardDescription>
            </CardHeader>
            <CardContent>
              <form className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="name">Guest Name</Label>
                  <Input id="name" placeholder="Enter guest name" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="contact">Contact Info</Label>
                  <Input id="contact" placeholder="Enter contact info" />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="arrival">Arrival Date</Label>
                    <Input id="arrival" type="date" />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="departure">Departure Date</Label>
                    <Input id="departure" type="date" />
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="requests">Special Requests</Label>
                  <Textarea id="requests" placeholder="Enter any special requests" />
                </div>
                <Button type="submit">Add Guest</Button>
              </form>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Access Management</CardTitle>
              <CardDescription>Manage digital keys and passes for your guests.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Digital Keys Issued</div>
                    <div className="text-gray-500 dark:text-gray-400">12 active keys</div>
                  </div>
                  <Button size="sm" variant="outline">
                    Manage Keys
                  </Button>
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Guest Passes Issued</div>
                    <div className="text-gray-500 dark:text-gray-400">8 active passes</div>
                  </div>
                  <Button size="sm" variant="outline">
                    Manage Passes
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="col-span-1 md:col-span-2 lg:col-span-3">
            <CardHeader>
              <CardTitle>Analytics</CardTitle>
              <CardDescription>Track guest activity and usage of the system.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="flex flex-col gap-2">
                  <div className="text-4xl font-bold">1,234</div>
                  <div className="text-gray-500 dark:text-gray-400">Total Guests</div>
                </div>
                <div className="flex flex-col gap-2">
                  <div className="text-4xl font-bold">85%</div>
                  <div className="text-gray-500 dark:text-gray-400">Occupancy Rate</div>
                </div>
                <div className="flex flex-col gap-2">
                  <div className="text-4xl font-bold">$12,345</div>
                  <div className="text-gray-500 dark:text-gray-400">Total Revenue</div>
                </div>
              </div>
              <Separator className="my-6" />
              <LineChart className="aspect-[16/9]" />
            </CardContent>
          </Card>
        </main>
      </div>
    </div>)
  );
}

function BarChartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>)
  );
}


function BellIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>)
  );
}


function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function KeyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4" />
      <path d="m21 2-9.6 9.6" />
      <circle cx="7.5" cy="15.5" r="5.5" />
    </svg>)
  );
}


function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
