/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MNNp5WuXH39
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";

export function RegistrationForm({ onSubmit, client }) {
  const [loading, setLoading] = useState(false);
  return (
    <div
      className="mx-auto max-w-md space-y-6 py-12"
      style={{ width: "600px" }}
    >
      <div className="space-y-2">
        <h1 className="font-bold">Guest Registration</h1>
      </div>
      <form
        className="space-y-4"
        onSubmit={async (e) => {
          e.preventDefault();
          setLoading(true);
          const first_name = e.target["0"].value;
          const last_name = e.target["1"].value;
          const email = e.target["2"].value;
          const phone = e.target["3"].value;
          const address = e.target["4"].value;

          try {
            await client.verification.save({
              step: "PersonalInfo",
              data: {
                email,
                full_name: `${first_name} ${last_name}`,
                phone,
                address,
              },
              complete: true,
            });
            onSubmit();
          } catch (err) {
            console.error(err);
          } finally {
            setLoading(false);
          }
        }}
      >
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">First Name</Label>
            <Input id="first-name" placeholder="John" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Last Name</Label>
            <Input id="last-name" placeholder="Doe" required />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="m@example.com" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="phone">Phone</Label>
          <Input
            id="phone"
            placeholder="+1 (555) 555-5555"
            required
            type="tel"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="address">Address</Label>
          <Textarea
            id="address"
            placeholder="123 Main St, Anytown USA"
            required
          />
        </div>
        <Button className="w-full" type="submit" loading={loading}>
          Register
        </Button>
      </form>
    </div>
  );
}
